<style type="text/css">
@media screen and (min-width: 960px){div.main{width:864px; margin:8px auto; padding:8px; display:block; background-color:#fff;}}
@media screen and (max-width: 960px){div.main{width:96%; margin:8px auto; padding:8px; display:block; background-color:#fff;}}
img{display: inline-block; height: auto; max-width: 100%; margin:8px auto;}
</style>
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?5e78d58dd74623a0970d8bab7f31e370";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
